name: Deploy ReactJS First Hire Frontned
on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}     
      - name: Build Docker Image
        run: docker build -t chubbsbunns/first-hire-frontend --build-arg VITE_WEB_BASE_URL='http://122.248.194.104:5173' --build-arg VITE_API_BASE_URL='http://122.248.194.104:3001' --build-arg VITE_AUTH_DOMAIN_URL='dev-dwtvfqfln7z0evht.us.auth0.com' .
      - name: Publish Image to docker hub
        run: docker push chubbsbunns/first-hire-frontend:latest
 
 
  deploy:
    needs: build
    runs-on: self-hosted 
    steps:  
      - name: Pull image from docker hub
        run: docker pull chubbsbunns/first-hire-frontend:latest
      - name: Delete old container
        run: docker rm -f first-hire-frontend
      - name: Run Docker Container
        run: docker run -d -p 5173:80 --name first-hire-frontend -e MONGO_PASSWORD='${{ secrets.MONGO_PASSWORD }}' chubbsbunns/sfirst-hire-frontend